Lazy loading & concurrent loading limiting for previews
peopledoc/dragndoc pull request #13
Opened 2016-10-05 17:10 UTC by amessinger

review @xcambar

2016-10-05 17:11 UTC, amessinger commented
question: should this PR really be merged into v1? or should we create a new one within GH?

2016-10-05 17:22 UTC, aRkadeFR commented on README.rst
> +Small PDF splitter application based on DragNDoc splitpdfapp.com http://splitpdfapp.com
I don't see anything on the URL

2016-10-06 08:50 UTC, amessinger commented on README.rst
> +Small PDF splitter application based on DragNDoc splitpdfapp.com http://splitpdfapp.com
My editor removed a trailing space character on his own. I don't know a thing about this url, the project it is supposed to link to...

2016-10-06 11:57 UTC, kintso commented
Could you put the same loader as displayed on http://webmenu.org/apps/splitpdfapp : ) ?

2016-10-06 12:01 UTC, amessinger commented
I can't see any loader (and I thought about it but I'm lazy :p )

2016-10-06 16:50 UTC, amessinger commented
@kintso Ok, I'm such a good samaritan. Here's your loader.

2016-10-07 07:03 UTC, xcambar requested changes
Code LGTM, but I still need to test it.

2016-10-07 07:03 UTC, xcambar commented on app/application.coffee
> +    maxConcurrentLoadingPages = false
You can use `Infinity`, it allows to only rely on numbers in your code below.

2016-10-07 07:03 UTC, xcambar commented on app/models/page.coffee
> +        return not @maxConcurrentLoadingPages or @where({loading: true}).length < @maxConcurrentLoadingPages
You can remove `not @maxConcurrentLoadingPages or` if you use `Infinity` (see my comment above)

2016-10-07 08:46 UTC, amessinger commented on app/models/page.coffee
> +        return not @maxConcurrentLoadingPages or @where({loading: true}).length < @maxConcurrentLoadingPages
True! Thanks :)

2016-10-10 11:13 UTC, xcambar approved these changes

2016-10-10 11:13 UTC, xcambar commented
Tests fail because of:
> Could not find .travis.yml, using standard configuration.

Can you fix it?

2016-10-10 13:45 UTC, merged